### ISSUE TITLE
Should be able to see queues from dashboard itself

### ISSUE THREAD

**Issue by saurabh-vyas** [yobnytech/queueone_issues_tracker#1]
QCorddintor web app - We see 'NO. of Queues' card on dashboard, we should be able to click on that and see the list of queues. For now one has to click : Queues -> ViewQueues (less intuitive)

**Comment by yobnytech** [comment]
Baileywick new Partner web theme has planned which will open up the Queues as the dashboard.

**Comment by yobnytech** [comment]
The feature provided in the Baileywick Partner WebInterface
