### ISSUE TITLE
Total visiting not shown correctly on eToken

### ISSUE THREAD

**Issue by qonelead** [yobnytech/queueone_issues_tracker#103]

**Comment by yobnytech** [comment]
Fixed, plz test and close

**Comment by qonelead** [comment]
If the expectation is that on Mobi token we should not show total visiting, then this can be closed.
BTW we do show total visiting on mw.queueone token link, so for consistency we should have both showing same contents.

**Comment by qonelead** [comment]
Closings this issue and creating new issue to add total visiting on mobi token.
