### ISSUE TITLE
Issue with mobile no. validation on mobi site

### ISSUE THREAD

**Issue by qonelead** [yobnytech/queueone_issues_tracker#105]
As reported by UAT team

     System doesn’t accept mobile number inspite entering correct number. Scenerio While slot booking, after selecting stores once mobile number entered starting with +91 dialogue box, if user enter incorrect mobile then system prompt again dialogue box to enter mobile +165XXXX then doesn’t processed / allow until URL not refreshed.

**Comment by qonelead** [comment]
Have not noticed this again today, thus closing it (BTW one of the customer reported that today, assuming that might be intermittent ntw issue for them)

**Comment by qonelead** [comment]
Closed incorreclty .. opening again (as missed looking into issue reported by Govardhan).
Read 1st comment for more info

**Comment by yobnytech** [comment]
Test and close

**Comment by qonelead** [comment]
There is still one issue pending here.
Click on my tokens, text box to enter phone number appears.
Press cancel, it does not take back to prev page, instead the spinner just circles and stay on that page

**Comment by yobnytech** [comment]
Fixed please test and close

**Comment by qonelead** [comment]
Verified
