### ISSUE TITLE
In correct wait time shown on mobi site token

### ISSUE THREAD

**Issue by qonelead** [yobnytech/queueone_issues_tracker#106]
As reported by UAT team

Hours left on Booked Slot is incorrect, Slot booked for tomorrow 3 to 4 pm today @ 16.38 hrs it should hours selft as 13 Hrs.

**Comment by yobnytech** [comment]
Removed that grouping, fixed test and close

**Comment by qonelead** [comment]
Booked token for tomorrow on mobi site. It shows only slot time but do not show date for booking

![image](https://user-images.githubusercontent.com/61919696/90310006-ff0e0f80-df0a-11ea-8e0b-779a6680eca3.png)

**Comment by qonelead** [comment]
closing this issue and opening new issue for capturing date on the mobi token
