### ISSUE TITLE
Fetching my-token on mobi site has issues

### ISSUE THREAD

**Issue by qonelead** [yobnytech/queueone_issues_tracker#108]
If one try to fetch token without having any valid Token on then mobi site, then after providing phone no, no OTP appears and cancelling phone no. text box shows no valid Token.

![Screenshot_20200814-204758](https://user-images.githubusercontent.com/61919696/90266000-0254bd00-de71-11ea-80d7-0aad4779ac9e.jpg)

**Comment by yobnytech** [comment]
Fixed test and close

**Comment by qonelead** [comment]
So I could fetch my token, but that pulled all tokens for me (even expired ones from all queues).
It should fetch only valid tokens for a customer.

![image](https://user-images.githubusercontent.com/61919696/90310054-8491bf80-df0b-11ea-838e-a56d1b8b3925.png)

**Comment by qonelead** [comment]
Closing this issue and opening a new one for token being fetched from diff partner too
