### ISSUE TITLE
Token Display need fixing

### ISSUE THREAD

**Issue by saurabh-vyas** [yobnytech/queueone_issues_tracker#11]
For now, if we do not supply email for a customer, we take their phone no as email id, i.e.
<phone-no>@gmail.com

We display such email (which in not actual email) on Token too. While we can use such made-up email for an internal purpose, we should not be displaying that on Token (on partner side).

Apart, the name of customer should be shown bigger (and not the token number).

**Comment by yobnytech** [comment]
Token Display in the Coordinator App will be Considered as follows 

      [ User Personal Details (DisplayName / First Name + Last Name / Phone Number / Email ]
      Token Details
