### ISSUE TITLE
Need better labels for partner app dahsboard.

### ISSUE THREAD

**Issue by qonelead** [yobnytech/queueone_issues_tracker#116]
Here are some suggestions:

Open Checked-In --> Total Patrons inside

Total Checked-In --> Check-Ins
Total Online Booking --> Online
Total Walkin Booking --> Walkins (including Anon)
Cancelled Booking --> Cancellations

New Label needs to be added:
Checkout

**Comment by yobnytech** [comment]
Open Checked-In --> Currently Serving

Total Checked-In       --> Check-Ins
New                           --> Check-Outs
Total Online Booking --> Pre Bookings
Total Walk-in Booking --> Walk-Ins 
Cancelled Booking      --> Cancellations

**Comment by qonelead** [comment]
Looks good.
