### ISSUE TITLE
Error msg can be improved when trying to book when no slots are available

### ISSUE THREAD

**Issue by qonelead** [yobnytech/queueone_issues_tracker#120]
The msg could say:
"No slots available currently, please select next available slot."

Currently us says (and has typo too)

![Screenshot_20200816-002805](https://user-images.githubusercontent.com/61919696/90319665-c5afc100-df57-11ea-807b-2fe58433044b.jpg)

**Comment by yobnytech** [comment]
Fixed and will be released 16th August

**Comment by qonelead** [comment]
Verified
