### ISSUE TITLE
Inconsistencies in partner app dashboard

### ISSUE THREAD

**Issue by qonelead** [yobnytech/queueone_issues_tracker#123]
Following inconsistencies seen on dashboard

- currently serving shows no. of tokens in checkin state.
It shd consider total visiting 

- checkin & check-out in current current slot shd be no. Of Token added and moved out. For now, checkin count reduced when check-out happens.

![Screenshot_20200816-132356](https://user-images.githubusercontent.com/61919696/90329593-d138d180-dfc3-11ea-9d5e-1b4eaff905ea.jpg)

**Comment by yobnytech** [comment]
Regression bug introduced in last night release.

**Comment by qonelead** [comment]
Yet seeing issues.
Added token with 3 visiting.
Before checkin itself dashboard shows Currently serving as 3

![Screenshot_20200817-001959](https://user-images.githubusercontent.com/61919696/90341739-98c6e100-e01f-11ea-8f40-86c74008a40a.jpg)

**Comment by qonelead** [comment]
Verified
