### ISSUE TITLE
CSV file upload should be flexible & eaiser

### ISSUE THREAD

**Issue by saurabh-vyas** [yobnytech/queueone_issues_tracker#2]
QCorddintor web app - When we try and upload a CSV file, it requires a particular format. The upload window should tell about format (<Name>,<Email:optional>,<mobile-no>,<time:optional>)

For now, One of user user-case has : Name, Phone-no, Time

**Comment by yobnytech** [comment]
Possible Options:

1. They can download the template from the front-end and generate the upload template.

2. We can give an option while creating a queue, to set the Upload CSV format by queue provider so that it will be flexible

**Comment by yobnytech** [comment]
Option 2 has been implemented in the partner web, in the Queue Setting partner can define the Queue upload file format and upload the appointment details.
