### ISSUE TITLE
client search  does not work in partner web

### ISSUE THREAD

**Issue by qonelead** [yobnytech/queueone_issues_tracker#27]
Not able to search a client in partner web. The client name exists, but search does not find a match for that.
Tried this in Q for Little Blue Jays

**Comment by yobnytech** [comment]
Problem with the first letter, for example, "Rahul" can be searched with the word "ahul" which need fixing.

**Comment by yobnytech** [comment]
Fixed

**Comment by qonelead** [comment]
Yet some discrepancy. 
In LBJ, we have created a new subscription for new customer 'Anirudh Sushruth'
Now this name is not even present in the client list.
Any new customer should appear in client list & be searchable.

**Comment by yobnytech** [comment]
Fixed please test and close
