### ISSUE TITLE
[ QueueOne User App ] Expired Token not Visible in the Token detailed view

### ISSUE THREAD

**Issue by yobnytech** [yobnytech/queueone_issues_tracker#30]
Token list view flags the expired tokens, but not visible once the token opened in the detailed view.

**Comment by yobnytech** [comment]
If a token is expired user won't able to click and move to the token details view.

**Comment by yobnytech** [comment]
will  be fixed in 1.0.18  version

**Comment by qonelead** [comment]
Verified. Can be closed.
