### ISSUE TITLE
Queue settings page need changes 

### ISSUE THREAD

**Issue by qonelead** [yobnytech/queueone_issues_tracker#37]
When changing a queue setting, like marking q as bookable, we need following things:
- user to be notified for changes being saved
- changes should be reflected without requiring hard refresh

Other scenario:
- Bookings & Availability tab: Hrs & Min drop down shd be side-by-side

**Comment by yobnytech** [comment]
- user to be notified for changes being saved  - Fixed
- changes should be reflected without requiring hard refresh - Fixed

**Comment by yobnytech** [comment]
Bookings & Availability tab: Hrs & Min drop down shd be side-by-side - might be CSS issues in FireFox browser, please test in Chrome and share the result.

**Comment by qonelead** [comment]
Test both issues (user notified & no hard refresh). Works as expected.
Hrs & Min drop down shows fine on Chrome. Issue only appears in FF.

One more issue surfaced, adding it here (related to setting changes), need clarification (and not opening new issue).
- Initially Q was FIFO
- Added 4 walkin users
- changed q settings to be a Bookable
- Added users disappeared (not sure about what is right expected behavior; ideally .. it should prompt to empty user or tell that existing users will be removed)
- Changed Q back to FIFO, the added users re-appeared (as expected)

**Comment by qonelead** [comment]
Closing this issue as verified, creating new issue for additional use case
