### ISSUE TITLE
Customer name not adding correctly while adding a walkin

### ISSUE THREAD

**Issue by qonelead** [yobnytech/queueone_issues_tracker#40]
When we add a walkin from partner web, the customer name given as "first-name last-name"
But it appears in the queue as "first-name last-name first-name last-name"

**Comment by yobnytech** [comment]
It might for some customers who were added/joined months before we will give option in client listing to correct the entries.

**Comment by qonelead** [comment]
Not seeing this issue for new walkins, thus closing this issue.
