### ISSUE TITLE
New registration lands to dashboard of last active login

### ISSUE THREAD

**Issue by qonelead** [yobnytech/queueone_issues_tracker#41]
When a new partner is registered, they lands up to dashboard of partner with last active login.
This is a security issue, as no one should be able to get details of one partner without using credentials.

**Comment by yobnytech** [comment]
Agreed, will be fixed in the upcoming release.

**Comment by qonelead** [comment]
Tested again, so now I do not see the queues from older login, but the queue-drop-down still shows name of queue from older login.
New partner: New Horizon
Old partner: Classic Spa & Hair Salon
Attaching image for ref.

![image](https://user-images.githubusercontent.com/61919696/76684412-e3d46680-6631-11ea-9c83-c164a68a6405.png)

**Comment by yobnytech** [comment]
Fixed

**Comment by qonelead** [comment]
Yet seeing the queue-name from old login when created new partner.
Old login : Classic Salon
New partner : Sajan Salon

![image](https://user-images.githubusercontent.com/61919696/76708373-3db15b00-671c-11ea-989d-12c7dc39dc4b.png)

**Comment by yobnytech** [comment]
Fixed and reset will happen on the login switch - need to test

**Comment by qonelead** [comment]
Will avoid creating a dummy partner for this. 
Will run this test when have to add new partner (hopefully in a day or two). 
Will update this issue after verifying (and close as needed).

**Comment by yobnytech** [comment]
Fixed
