### ISSUE TITLE
Incorrect numbering for service counter on partner web

### ISSUE THREAD

**Issue by qonelead** [yobnytech/queueone_issues_tracker#42]
Created 6 counters for Q at Classic Salon. The number for counter shown as:

Counter 0 | Counter 0 | Counter 1 | Counter 2 | ... | Counter 4

Counter 0 is repeated, and ideally we should have Counter no started from 1

**Comment by yobnytech** [comment]
Fixed

**Comment by qonelead** [comment]
Not verifying this as once counter are created, they need to be cleaned from backend. This closing as verified by developer.
