### ISSUE TITLE
No checkin option shown for FIFO Q

### ISSUE THREAD

**Issue by qonelead** [yobnytech/queueone_issues_tracker#44]
Tried this in Classic Salon Q
- Created 6 counters
- Added 2 test users
- Started the Q (before that it was running in invisible mode)
- Went to token view page, but no option to check-in (see attached)

![image](https://user-images.githubusercontent.com/61919696/76688354-f3fc3e00-6651-11ea-9f53-60151fd81dda.png)

**Comment by yobnytech** [comment]
Checkin is allowed in the following cases

  1. the logged-in person should be either have a manager role or allocated to the service counter
  2. the queue should be in the un-available state.

**Comment by qonelead** [comment]
Verified. Closing this issue
