### ISSUE TITLE
Token display should not show dummy email id

### ISSUE THREAD

**Issue by qonelead** [yobnytech/queueone_issues_tracker#45]
While adding a walkin, if we give only the first_name, then the token is shown with dummy email id, i.e.
<phone-no>@gmail.com (see attached).

No email is shown if we provide <Fname Lname> for walkin user

![image](https://user-images.githubusercontent.com/61919696/76688435-c19f1080-6652-11ea-9694-db2664fe57bd.png)

**Comment by yobnytech** [comment]
We are not showing any mail which is made-up like @queueone.com, @mail.com @gmail.com is supposed to be a valid email.

**Comment by yobnytech** [comment]
Fixed

**Comment by qonelead** [comment]
Verified the fix, closing
