### ISSUE TITLE
Failed to add walk-in user in partner mobile app

### ISSUE THREAD

**Issue by qonelead** [yobnytech/queueone_issues_tracker#46]
Adding a walk-in user from partner mobile app fails.

**Comment by qonelead** [comment]
It seems Adding a walk-in is making email as mandatory field. If we provide email we are able to add walk-in user. But this seems unlikely for use cases like salons.

**Comment by yobnytech** [comment]
fixed

**Comment by qonelead** [comment]
Verified in newer version of app. Works fine. Closing this one
