### ISSUE TITLE
User app does not show correct queue stats while one is taking a position

### ISSUE THREAD

**Issue by qonelead** [yobnytech/queueone_issues_tracker#47]
For Classic Salon Q, I had :
- 2 ppl checked-in
- 1 taken the position (added walkin)

then tried to take a position from user app. It showed '0 waiting', but when took the position it gave position '2' (which is correct).

I refreshed the app before taking position (closed and open again), but still it was showing '0'

**Comment by yobnytech** [comment]
Fixed in the backend
