### ISSUE TITLE
QCoordinator: Partner Auth Token is not refereshing

### ISSUE THREAD

**Issue by yobnytech** [yobnytech/queueone_issues_tracker#5]
After some time the QCoordinator authentication token is not refreshing buy itself. It requires manual operation to refresh, need a hard refresh and auto firebase token refresh functionality should work.

**Comment by yobnytech** [comment]
Fixed

**Comment by qonelead** [comment]
Did not faced this issue in the local build of coordinator app. Thus this is good to be closed.
