### ISSUE TITLE
Partner app not shoing checkin option for test-real-time-Q

### ISSUE THREAD

**Issue by qonelead** [yobnytech/queueone_issues_tracker#55]
Something seems to be broken in Test-realtime-Q (our test Qs)
It does not show option to do checkin in partner web
One can checkin/checkout using partner app

**Comment by yobnytech** [comment]
Should have been fixed

**Comment by qonelead** [comment]
Ok, so this yet not show check-in option.
Logged in using : yobnytech@gmail.com
Real time queue yet not showing 'checkin option' in partner web.

![image](https://user-images.githubusercontent.com/61919696/77233226-29fa6e80-6bcc-11ea-8e47-5586b6978905.png)

**Comment by yobnytech** [comment]
Fixed, logged in user didn't have access/role to check-in
