### ISSUE TITLE
One should not get error msg when they cancel joining the Queue in between

### ISSUE THREAD

**Issue by qonelead** [yobnytech/queueone_issues_tracker#56]
User might not provide inputs during Queue joining process, and cancel that. They might press the back key (android soft key). In both cases one gets error msg " Failed to get the position".
They should get different msg here (not error)

**Comment by yobnytech** [comment]
Fixed

**Comment by qonelead** [comment]
Tested this, this work fine when we cancel in between providing the user inputs.
But this does not work fine when we hit cancel during slot selection in bookable q
This use case should be addressed too.
