### ISSUE TITLE
Cancel button for walk-in does not work in partner app

### ISSUE THREAD

**Issue by qonelead** [yobnytech/queueone_issues_tracker#59]
In testqueue, clicked on add walk-in --> selected slot --> pressed cancel.
Cancel does not work.

**Comment by yobnytech** [comment]
Fixed will be available in next release.

**Comment by qonelead** [comment]
As discussed, here is what we would need as expected behavior (when one try to add a walkin):
- Cancel should move back to token list view (canceling add walkin action)
- When partner adds a walkin, move back to list view (showing the newly added token too)
[ we now feel that user will not be adding many walkin users at once, and this will make web app & mobile app behavior consistent ]

**Comment by yobnytech** [comment]
Ok, Fixed that. Please test in new release

**Comment by yobnytech** [comment]
Closed
