### ISSUE TITLE
User not seeing immendiate next avaialble slot in lite desc web

### ISSUE THREAD

**Issue by qonelead** [yobnytech/queueone_issues_tracker#63]
When user try to book slot using lite desc web, they do not see next immediate open slot. I.e.
if use trying at 3:05 pm, they will see slot of 4pm onwards, and do not see 3:30 pm slot (for 30 min slot duration)

**Comment by yobnytech** [comment]
I think this issue is with user app, provided updated build please test.

**Comment by qonelead** [comment]
Verified. Closing
