### ISSUE TITLE
Partner app should have option to show details provided by user upon a successful scan

### ISSUE THREAD

**Issue by qonelead** [yobnytech/queueone_issues_tracker#82]
Currently, after a user Token is scanned by partner app, we only show if the person is on time early/late. If we have user inputs collected while joining q, we shd ve option to display them.

**Comment by yobnytech** [comment]
Yes, we need to show the details of the input provided.

**Comment by yobnytech** [comment]
Provided

**Comment by qonelead** [comment]
Verified
