### ISSUE TITLE
Display issue on Token listing page in SaaS platform

### ISSUE THREAD

**Issue by qonelead** [yobnytech/queueone_issues_tracker#84]
SO for a FIFI Q, we have input parameters (mandatory).
For some tokens our SaaS platform shows the input parameters, and for some it does not.

The captured image shows one such instance.

![image](https://user-images.githubusercontent.com/61919696/80349464-e959d900-888c-11ea-8ff0-09e12b4bdb71.png)

**Comment by yobnytech** [comment]
Fixed and Released
