### ISSUE TITLE
Partner app display issues

### ISSUE THREAD

**Issue by qonelead** [yobnytech/queueone_issues_tracker#85]
- Token listing shd not have @gmail.com
- We shd mask phone no in Token display in partner app (77XXXXX123)
- Token count not appearing correct on top right
- it always shows guest user logged in
![Screenshot_20200523-095748__02](https://user-images.githubusercontent.com/61919696/82721717-8fa6cc00-9cdd-11ea-90ae-455a2c2766a1.jpg)

**Comment by yobnytech** [comment]
- Token listing shd not have @gmail.com - Changed to @mail.com

- Token count not appearing correct on top right - Fixed

- it always shows guest user logged in - Only happens for when the login is not successful.

**Comment by qonelead** [comment]
Verified. All fixed
