### ISSUE TITLE
Token link showing bad request even for vaild token.

### ISSUE THREAD

**Issue by qonelead** [yobnytech/queueone_issues_tracker#90]
![Screenshot_20200728-185221](https://user-images.githubusercontent.com/61919696/88671302-c3e6a080-d103-11ea-95b6-a6364382b180.jpg)

Link used here is: 
digital Token: https://tinyurl.com/tknq1?t=TK34810AT

**Comment by yobnytech** [comment]
This can happen when failure in the Job server,

**Comment by qonelead** [comment]
Have not seen this one again, thus closing this issue.
