### ISSUE TITLE
Partner app shing next slot incorrectly

### ISSUE THREAD

**Issue by qonelead** [yobnytech/queueone_issues_tracker#95]
When we cross last of the day, the next slot shd say tomorrow. Currently is says last slot time only (which could be before current time)
![Screenshot_20200808-183818](https://user-images.githubusercontent.com/61919696/89734935-b246b680-da7c-11ea-9a69-8d0a6e151e97.jpg)

**Comment by yobnytech** [comment]
Fixed, if next slot time is less than current time then tomorrow will be disabled

**Comment by qonelead** [comment]
We see that the next slot is dropped from display, thus good to close this issue.

**Comment by qonelead** [comment]
Ok, next slot shown correctly as tomorrow (when we enter last slot of current day).
But this label is not shown everytime (not sure why)
