### ISSUE TITLE
Notice next functionality should be dropped from list button in partner app

### ISSUE THREAD

**Issue by qonelead** [yobnytech/queueone_issues_tracker#98]
Queue coordinator will switch between dashboard and list page, if one click twice, it sends notice to next customer. It can also trigger SMS.

**Comment by yobnytech** [comment]
Better we will change the functionality to work only for Online Booking

**Comment by yobnytech** [comment]
Okay, for bookable notice functionality is disabled.

**Comment by qonelead** [comment]
Verified
